language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run format:test
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: bOlI2ITWnoanDAzCkmVKdCo/SpA/HNamTuiv3mnjx4PPi1y2jd/VZ0Pujp18E/pCVbf2/rY9e4rTCG7kqpnkWqTdXMA8N1J7iFBAeF620D9IwrSUUXQlCN04JhzRPo8aeDAPQrB2ecmz4QrKft4aRMUnNEVPxV31+e3xXkdShJSNXFTYUoW34wIkjJUKxIcR0ag7QCZyezzZpad4ZoRBEUG5UAgxLKGICr6qKo6D16D4UDDsSWx8bEhTtvZw6JObPHkxfdP0SZXfbUP/zkzIefZiV/qUuMOfbB2vDLKMfanRBZM3am0A4eb3WwqnZ4ElWP/ViqhkGW1iP95yMq0Sj4SrPNvAxJ/0eo9IYneYlkfUV0LFRrSdaPUajvoyVy2x/m0xvbMEpZ1xV3TzgL7Jpz5QMz8QqUtC6gTYJarczYEoT3ORvgFWb4PGTrSZ9poSQtEX5l/jiPWGW5dlWF13igofdbkayaDhbwJToAj52oFYt0LGPYD410ZPRrdCjZ1zKPIKF05o4ruz5Qd8MMpK2QvMg/5+xjRQEr4lcEK0yZqTP83yAYsNUExzWdUIFcXJ4+g+fTTphO4Pbu3uk0NCwv9HtBAQxOPOc+qV5WSlkTwtrPkaP2oRtiOUFcJZAb6arkl/lLEHC+bhKfDpEFqm5ASd6NNItRlYMxlF0kbLYbo=
  on: master
